// src/app/stock/[symbol]/FundamentalTab.jsx
// Why: Render fundamental analysis markdown generated by Gemini API in a dark modern card wrapper.
import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function FundamentalTab({ symbol }) {
  const [markdown, setMarkdown] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchMarkdown = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(`/api/fundamental?symbol=${symbol}`);
        const json = await res.json();
        if (!res.ok) throw new Error(json.error || '無法載入基本面分析數據');
        setMarkdown(json.markdown);
      } catch (err) {
        console.error('Error loading fundamental markdown:', err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchMarkdown();
  }, [symbol]);

  if (loading) {
    return (
      <div className="border border-slate-900 bg-slate-900/30 rounded-2xl p-12 flex flex-col items-center justify-center space-y-4 backdrop-blur-sm">
        <svg className="animate-spin h-10 w-10 text-indigo-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
        <p className="text-slate-400 text-base font-medium animate-pulse">
          Gemini 華爾街資深分析師正為您生成 {symbol} 完整基本面報告…
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="border border-red-900/50 bg-red-950/20 rounded-2xl p-8 text-center backdrop-blur-sm">
        <h3 className="text-lg font-bold text-red-400 mb-2">基本面分析載入失敗</h3>
        <p className="text-sm text-slate-400">{error}</p>
      </div>
    );
  }

  return (
    <div className="border border-slate-900 bg-slate-900/30 rounded-2xl p-6 sm:p-8 backdrop-blur-sm shadow-xl">
      <div className="flex items-center justify-between border-b border-slate-800/80 pb-4 mb-6">
        <div className="flex items-center gap-3">
          <span className="text-2xl">🏛️</span>
          <div>
            <h2 className="text-lg font-bold text-slate-100">{symbol} 華爾街資深基本面報告</h2>
            <p className="text-xs text-slate-500">由 Google Gemini 結合即時網路檢索分析生成</p>
          </div>
        </div>
        <span className="px-3 py-1 text-xs font-medium rounded-full bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
          AI 深度報告
        </span>
      </div>

      <div className="prose prose-invert max-w-none text-slate-200 text-sm leading-relaxed space-y-4">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
      </div>
    </div>
  );
}
